version: 2.1
jobs:
  run-tests:
    docker:
      - image: circleci/node:12.4-browsers
    steps:
      - checkout
      - run:
          name: download deps
          command: npm i
      - run:
          name: run selenium test
          command: npm run ui-test

  publish:
    docker:
      - image: circleci/node:12.4
    steps:
      - checkout
      - run: npm i
      - run: sudo npm i -g vsce
      - run: vsce publish -p $AZURE_TOKEN

workflows:
  version: 2.1
  verify:
    jobs:
      - run-tests

  publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
