version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.4-browsers
    steps:
      - checkout
      - run:
          name: download deps
          command: npm i
      - run:
          name: run selenium test
          command: npm run ui-test
